title: Todd Jordan - Data Scientist
description: Senior Data Scientist & Engineering Analytics Expert - Driven by curiosity and passion for improving systems through efficiency gains
baseurl: ""
url: "https://tnjordan.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - dev.txt

# Include files
include:
  - assets

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
author:
  name: Todd Jordan
  email: contact@tnjordan.github.io
  linkedin: https://www.linkedin.com/in/connect-todd/
  github: https://www.github.com/tnjordan/
