theme: jekyll-theme-leap-day
title: Todd Jordan
description: An engineering data scientist, driven by curiosity and a passion for improving systems through efficiency gains.
# # description
# markdown: GFM